In [1]:
f = open("a.txt")

FileNotFoundError: [Errno 2] No such file or directory: 'a.txt'

In [2]:
#try and except

In [3]:
try:
    f = open('all.txt')
except:
    print("file does not exist")

file does not exist

In [1]:
try:
    f = open('a1.txt')
    print(var1)
except:
    print("file does not exist")

file does not exist

In [2]:
try:
    f = open('a1.txt')
    print(var1)
except FileNotFoundError:
    print("file does not exist")

NameError: name 'var1' is not defined

In [3]:
try:
    f = open('a1.txt')
    print(var1)
except FileNotFoundError:
    print("file does not exist")
except Exception:
    print("something went wrong")

something went wrong

In [4]:
try:
    f = open('a1.txt')
    print(var1)
except FileNotFoundError:
    print("file does not exist")
except Exception as e:
    print(e)

name 'var1' is not defined

In [4]:
try:
    f = open('a1.txt')
except FileNotFoundError:
    print("File does not exist")
except Exception as e:
    print(e)
else:
    print(f.read())
    f.close()

This is first line

In [5]:
#finally block

In [5]:
try:
    f = open('a1.txt')
    print(var1)
except FileNotFoundError:
    print("File does not exist")
except Exception as e:
    print(e)
else:
    print(f.read())
    f.close()
finally:
    print("Run complete")

name 'var1' is not defined
Run complete

In [6]:
try:
    f = open('a1.txt')
    if f.name == 'a1.txt':
        raise Exception
except FileNotFoundError:
    print("File does not exist")
except Exception as e:
    print(e)
else:
    print(f.read())
    f.close()
finally:
    print("Run complete")

Run complete

In [7]:
f = open('a1.txt')
if f.name == 'a1.txt':
    raise Exception

Exception:

In [11]:
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
try:
    c = a / b
    print("Division: ",c)
except ZeroDivisionError:
    print("error: division by zero")
except ValueError:
    print("error: enter a valid number")

Enter first number:  15
Enter second number:  3

Division:  5.0

## Pandas

In [12]:
import pandas as pd

In [13]:
roll = pd.Series([1,2,3,4,5])
name = pd.Series(['Sia','Ravi','Geet','Ajeenkya','Avinash'])
marks = pd.Series([85,67,59,40,90])

In [14]:
df = pd.DataFrame({
    'id': roll,
    'name': name,
    'marks': marks
})

In [15]:
df

   id      name  marks
0   1       Sia     85
1   2      Ravi     67
2   3      Geet     59
3   4  Ajeenkya     40
4   5   Avinash     90

In [16]:
df.ndim

2

In [17]:
df.shape

(5, 3)

df.size

In [18]:
df.columns

Index(['id', 'name', 'marks'], dtype='object')

In [19]:
df = pd.read_csv("student.csv")
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [20]:
df.shape

(10, 5)

In [21]:
df.columns

Index(['roll', 'name', 'class', 'marks', 'age'], dtype='object')

In [22]:
df = pd.read_csv('student1.csv')
df

    1     anil  TE  56.77  22
0   2     amit  TE  59.77  21
1   3   aniket  BE  76.88  19
2   4  ajinkya  TE  69.66  20
3   5     asha  TE  63.28  20
4   6   ayesha  BE  49.55  20
5   7     amar  BE  65.34  19
6   8    amita  BE  68.33  23
7   9     amol  TE  56.75  20
8  10    anmol  BE  78.66  21

In [11]:
col = ['roll','name','class','marks','age']

In [12]:
df = pd.read_csv('student1.csv', names = col)
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [15]:
df = pd.read_csv('student3.tsv', sep = '\t')
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21